# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mon Jekyll test grunt
email: mailbox@lvdesign.com.fr
description: "It will appear in your document head meta (for
  Google search results) and in your feed.xml site description."
baseurl: /jekyllGrunt # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: lvdesign
github_username:  laurentvignaux

# Build settings
markdown: kramdown


exclude: [
  .git,
  .gitignore,
  .DS_Store,
  svg-icons,
  svg-decorations,
  scss,
  .sass-cache,
  package.json, 
  Gruntfile.js, 
  node_modules, 
  readme.md
]